### ISSUE TITLE
Liquid not correctly seeing new tag

### ISSUE THREAD

**Issue by joshkerr** [robb/jekyll-embedly-client#2]
I'm getting an error in my site when using this plugin:

Liquid error: undefined method `[]' for nil:NilClass

Here is my config.yml file parts for the plugin:

embedly: 
api_key: my_key_removed_for_security_reasons
vimeo:
width: 500px

**Comment by robb** [comment]
Hey Josh,

Do you have the json and domainatrix gems installed?
Also, could you try if the error persists with the kramdown markdown engine?
Just add `markdown: kramdown` to your _config.yml

**Comment by joshkerr** [comment]
Yes.  I was able to get it working by running Jekyll --no-auto --no-server.  For some reason running it with server causes it to fail.

**Comment by joshkerr** [comment]
Passing in the 500px didn't work either.  It seems to ignore those options.  (Which might be a clue to my difficulties.)

**Comment by robb** [comment]
That's very weird, I'd assume that `auto` and `server` have no effect on the rendering process.

Also, I use `width: 500` in my _config.yml for vimeo, without the px and this produces correct embeds for me.

Does `--server` work corrently if you don't use the embedly plugin?

**Comment by joshkerr** [comment]
I switched my jekyll install to octopress and the issue seemed to clear up.  Sorry I couldn't be more helpful.
