### ISSUE TITLE
Response does not contain HTML

### ISSUE THREAD

**Issue by dandunckelman** [robb/jekyll-embedly-client#4]
Cool plugin! I tried following your sample with this:

```
{% embedly  http://soundcloud.com/mightyoaksmusic/rainier, color: 00FFFF %}
```

But the "resolve" method DID NOT return the HTML key, so I end up with an empty div like this:

```
<div class="embed link soundcloud"></div>
```

So, I tried a vimeo embed like this:

```
{% embedly http://vimeo.com/18150336 %}
```

And that worked fine by producing this:

```
<div class="embed video vimeo"><iframe src="http://player.vimeo.com/video/18150336" width="1280" height="720" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe></div>
```

So....maybe something changed with soundcloud?

**Comment by robb** [comment]
Looks like the issue is simply that the track is no longer embeddable :-)
